FROM python:3.9

WORKDIR /code

COPY ./backend/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

COPY ./backend/ .

ENV PYTHONPATH "${PYTHONPATH}:/code/"

CMD ["python3", "main.py", "--port", "8000", "--workers=5"]