# Este workflow fará uma instalação limpa das dependências do node, armazenará em cache/restaurará as dependências, 
# construirá o código-fonte e executará testes em diferentes versões do node
# Para mais informações, veja: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Veja a programação de lançamentos suportados do Node.js em https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./docs
    - run: npm run build
      working-directory: ./docs
    - run: npm run test
      working-directory: ./docs
    - name: Serve website
      run: npm run serve
      working-directory: ./docs
